### ISSUE TITLE
Sort by Last Modified does not work

### ISSUE THREAD

**Issue by LtChae** [smartcitiesdata/discovery_ui#118]
**Expected behavior**: Most recently modified datasets at the top
**Actual behavior**: Some datasets appear at the top regardless of their updated date

**Comment by rob-h-m** [comment]
Blocking this while we review the business requirements for the "last modified" field with @ramboyapati

**Comment by rob-h-m** [comment]
This will be addressed by #199 which expands and clarifies the requirements
