### ISSUE TITLE
Datasets show Update Pending when they have ingested data

### ISSUE THREAD

**Issue by LtChae** [smartcitiesdata/discovery_ui#120]
**Current behavior:**
Update Pending is shown for datasets that have ingested data (and should therefore have modified dates)

**Expected behavior:**
Datasets that have ingested data should show the last day data was ingested.

**Comment by rob-h-m** [comment]
Blocking this while we review the business requirements for the "last modified" field with @ramboyapati

**Comment by rob-h-m** [comment]
This will be addressed by #199 which expands and clarifies the requirements
