### ISSUE TITLE
Document multi-dataset API

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/discovery_ui#132]
@jdenen commented on [Thu Jul 25 2019](https://github.com/smartcitiesdata/discovery_api/issues/175)

To help support users who want to query across datasets, we should document this API.

- [ ] Show example usage (`curl -X POST -d "select * from $table_name limit 10"` or something like it)
- [ ] Link to some SQL documentation
  - Presto docs?
  - More general SQL docs?
  - Both?
- [ ] Expose table name in dataset details page

**Comment by LtChae** [comment]
Proposed modification to the UI:

- Add table name to the list of metadata for the dataset
- Add the example query and additional documentation in the API example box
- Also add some text about how this API can be used to query across datasets (possibly with another example?)

Suggested documentation links:
- https://en.wikipedia.org/wiki/SQL_syntax
- https://www.w3schools.com/sql/sql_quickref.asp
- https://prestodb.github.io/docs/current/ (with some disclaimer that this the underlying datastore for the platform, and some additional querying features will be possible with its features)

How do we describe this API in our docs?  "Free-form Query API"?
