### ISSUE TITLE
GeoJSON Visualization does not zoom correctly for some datasets

### ISSUE THREAD

**Issue by sukaant** [smartcitiesdata/discovery_ui#140]
See dataset 746939c6_d007_403b_8868_7539a7d41924 (morpc) in staging.

Would you look at that? Just look at it.

**Comment by jdenen** [comment]
Edited your issue.

We should keep our staging URLs to ourselves.

**Comment by jdenen** [comment]
Also, this issue is hilarious. I think the zoom level is wonderful. 😂

**Comment by sukaant** [comment]
Good call - Ben
