### ISSUE TITLE
Create a "Download Data Dictionary" button on dataset details page

### ISSUE THREAD

**Issue by kennyatpillar** [smartcitiesdata/discovery_ui#144]
There is currently no way to download the complete schema for a dataset. There should be an easy way to download a schema definition from the dataset details page.

Refinement Notes: 

1. API needs to be created 
2. ~~Adhere to the PODMS~~
3. Format includes JSON only 
4. ~~Existing PODMS data.json includes url pointing to this dictionary~~

**Comment by abrock-accenture** [comment]
PODMS ACs will be moved to a new card: discovery-api #217
