### ISSUE TITLE
Data Dictionary IE11 Description Bug

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/discovery_ui#154]
The Data Dictionary description in IE11 get's cutoff with an ellipsis if it is too long.
https://discovery.smartcolumbusos.com/dataset/able-link/mapcd_trip_data

**Comment by smillardHNTB** [comment]
I found a few other IE11 bugs, maybe they can be grouped into one issue:
The visualize button is HUGE
The URL in the API example does not wrap correctly and extends the box boundary 

https://discovery.smartcolumbusos.com/dataset/usgs/usgs_wind_turbine_data

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #24](https://github.com/SmartColumbusOS/discovery/issues/24) via [**ZenHub**](https://www.zenhub.com/)
