### ISSUE TITLE
Update Current Joomla Site to Redirect to Discovery

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#160]
Currently, when a user navigates to the OS from the Smart Columbus landing page, it does not redirect to Discovery, which creates a lesser user experience.  The scope of this card is to update the redirect as a step towards removing iFrames from the UI.  

### Acceptance Criteria: 

- [ ] Main smartcolumbusos site does not iFrame the discovery UI into itself 
- [ ] smartcolumbusos.com/data 301 redirects to discovery UI
- [ ] The user is redirected to a properly branded discovery-ui
- [ ] The search box on the smart columbus homepage should redirect to discovery-ui with the search performed.
- [ ] Data story iframes will need reworked so menu-in-menu does not get displayed.  (Work with jake on the best way to design this experience)
- [ ] Run zap and should no longer see iFrame header. 

### Amigos: 

@jakeclark , @jeffgrunewald

**Comment by ManApart** [comment]
implemented in https://github.com/smartcitiesdata/discovery_ui/pull/243
