### ISSUE TITLE
Visualization page is SMRT branded

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/discovery_ui#164]
The `/visualization` page includes a SMRT logo. We don't want to couple the general platform and Smart Columbus.

<img width="465" alt="Screen Shot 2019-08-19 at 8 30 27 AM" src="https://user-images.githubusercontent.com/4671695/63265457-a8b8b300-c25b-11e9-9da6-06b9a3079ba2.png">

https://discovery.smartcolumbusos.com/dataset/odot/e3343a8d_4125_4243_b304_461a2e24af64/visualization

**Comment by abrock-accenture** [comment]
That logo is an optional logo that is passed into discovery_ui as an environment variable - if none is provided we don't show a logo at all.

**Comment by jdenen** [comment]
Well, then, nevermind. Thanks @abrock-accenture
