### ISSUE TITLE
Limit and alert the user that their queries are limited to 10,000 rows

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#179]
### Business Value: 

In order to maintain a high level of performance and fast load times, it was decided to limit the query result list to 10,000 rows for the purpose of visualizations.  The user will still have access to the complete dataset through separate download functionality.

### Acceptance Criteria: 

- [ ] The user is notified that query results are limited to 10,000 rows 
- [ ] The user is notified regardless of the query (static text below the query text box)
- [ ] The queries are limited to 10,000 rows (only for visualizations)
- [ ] Queries to the API remain unlimited
- [ ] @jakeclark has signed off on the UX 

### Amigos: 

@jakeclark

**Comment by rob-h-m** [comment]
We decided not to enforce this limit for the time being - closing
