### ISSUE TITLE
Add ability to fetch queries 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#180]
### Business Value: 

This is a first slice of creating the ability for users to save/share queries for future use.  The ultimate goal is to provide efficiencies for the end user so that coming to the platform will be a time-save for all of their data needs. 

### Acceptance Criteria: 

- [ ] User can retrieve query through a unique ID
- [ ] User cannot retrieve queries that they would not have access to run (this means private datasets for now)
- [ ] If the user has permission to view, when they go to the url including the unique ID, they are presented with the chart builder with the query and fetched data. 
- [ ] If the user does not have permission to view/the query doesn't exist, they are told that either the query doesn't exist or they do not have access to it.
- [ ] @jakeclark has signed off on the UX 

### Tech Notes: 

1. This can probably be achieved through the existing multi-query authorization 
2. Query IDs are stored in Redis for now

### Amigos: 

@jakeclark

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #8](https://github.com/SmartColumbusOS/discovery/issues/8) via [**ZenHub**](https://www.zenhub.com/)
