### ISSUE TITLE
Add ability to save queries 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#181]
### Business Value: 

This is a first slice of creating the ability for users to save/share queries for future use. The ultimate goal is to provide efficiencies for the end user so that coming to the platform will be a time-save for all of their data needs. 

### Acceptance Criteria: 

- [ ] Each time the user clicks the "save" button...
- [ ] They are presented with a unique url that they can copy - shown in a text box below the save button
- [ ] "Copy to clipboard" button next to the text box
- [ ] The user can fetch the query on the UI with the url they are given 
- [ ] @jakeclark has signed off on the UX 

Tech note:
- Store in Redis for now
- Play after retrieval card #180

### Amigos: 

@jakeclark

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #12](https://github.com/SmartColumbusOS/discovery/issues/12) via [**ZenHub**](https://www.zenhub.com/)
