### ISSUE TITLE
Add chart information to saved query data 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#182]
### Business Value: 

This is a first slice of creating the ability for users to save/share queries for future use. The ultimate goal is to provide efficiencies for the end user so that coming to the platform will be a time-save for all of their data needs. 

### Acceptance Criteria: 

- [ ] When the user saves a visualization, the structure of the chart is saved as well
- [ ] When the user retrieves the visualization, the structure of the chart is retrieved and presented in the UI 

#### Amigos

@jakeclark , @carriebrinkley , @LtChae

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #21](https://github.com/SmartColumbusOS/discovery/issues/21) via [**ZenHub**](https://www.zenhub.com/)
