### ISSUE TITLE
Activating mapbox for Plot.ly 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#184]
### Business Value: 

The next slice of integrating Plot.ly within the OS is to allow mapping functionality.  It has been determined that mapbox will be the best approach because we already have the API token.  Adding this functionality will allow users to visualize data on a map through Plot.ly. 

### Acceptance Criteria: 

- [ ] The mapbox API token has been activated for Plot.ly 
- [ ] It has been demonstrated that a map visualization can be created 

### Amigos: 

@LtChae , @jakeclark

**Comment by ManApart** [comment]
Mapbox has a bug with webpack that caused us some grief. Webpack minifies the source code with [terser](https://github.com/terser/terser#minify-options) which has a [compress option](https://github.com/terser/terser#compress-options) `typeofs` which (if not set to `false`) causes a runtime failure when mapbox is used.

**Comment by cameronmarsh** [comment]
https://github.com/plotly/plotly.js/issues/3768 reference for our workaround

**Comment by ManApart** [comment]
implemented in #196
