### ISSUE TITLE
Layering multiple queries into a singular query 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#185]
One of the business requirements for visualizations within the OS is that the ability exists to layer multiple datasets into a single visualization.  

### Scope/Questions to Answer: 

- [ ] What does it look like for us to layer multiple queries into a singular query for Plot.ly to create a visual? 
- [ ] @jeffgrunewald has signed off on the implementation details 
- [ ] Implementation details have been documented 

### Amigos: 

@jeffgrunewald

**Comment by ManApart** [comment]
Considered complete after discussion with Tim and Jeff. Multi-query cards have already been written.
