### ISSUE TITLE
ZAP security scan not scanning links/pages

### ISSUE THREAD

**Issue by smillardHNTB** [smartcitiesdata/discovery_ui#188]
It appears that the ZAP scan does not perform the active scanning of links on the page so it may not be scanning all links/pages.

Can we get ZAP to perform a more thorough scan of discovery-api via zap configuration or pointing at a specific endpoint or run script (list of pages to hit)

Tech note:
This may be due to the entire page being rendered in client side javascript and the index HTML not containing any links to page.

This could require reconfiguring ZAP, or changes to discovery UI.

**Comment by jakeprem** [comment]
We didn't find an easy flag or drop in replacement for using ZAP against Single Page Applications.

It appears that most people using ZAP for React and other SPAs are using it in conjunction with Selenium and other automated testing frameworks, using automated UI testing scripts that they have written.
