### ISSUE TITLE
Remove order by "Last Modified" from search 

### ISSUE THREAD

**Issue by smillardHNTB** [smartcitiesdata/discovery_ui#189]
Sorting does not work due to the modified metadata field having different formats.

Based on brief discussion, due to inconsistencies in the values of the modified fields in actual datasets (some are metadata modified, some are data modified) - it may be best to remove the sort until the data is consistent.  

Remove logic from API also

Based on research in https://github.com/smartcitiesdata/discovery_ui/issues/118

For more information:
@jakeprem @ramboyapati @LtChae @bbrewer-papa-x @smillardHNTB

**Comment by rob-h-m** [comment]
After discussion with @ramboyapati , the way in which "sort by last modified" should work was captured in #199
