### ISSUE TITLE
Possible JSON to CSV encoding issue

### ISSUE THREAD

**Issue by jakeclark** [smartcitiesdata/discovery_ui#195]
**Current State:** A JSON-to-CSV encoded file, when viewed as CSV, swaps column names when compared to the data preview. The JSON view shows the column headings normally. 

**Desired State:** Column Headings remain the same regardless of file type. 

Highlighted dataset: https://discovery.smartcolumbusos.com/dataset/central_ohio_transit_authority/a89e205c_3ee5_4eb4_948c_ea57e7eea587

![image](https://user-images.githubusercontent.com/430082/64203727-1f5fce00-ce62-11e9-855d-d715adcf3943.png)

![image](https://user-images.githubusercontent.com/430082/64203768-37375200-ce62-11e9-8fdd-5cf48ba2ea5b.png)

![image](https://user-images.githubusercontent.com/430082/64203936-94cb9e80-ce62-11e9-83c3-9d00b536a880.png)

**Comment by rob-h-m** [comment]
Note, this issue has been reported a couple of times by external users, who download CSV datasets and discover that the column headings are incorrect.
