### ISSUE TITLE
Update behavior of "Last Modified" in the list of datasets

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/discovery_ui#199]
As an OS data curator,
I want to change the way that "last modified" is handled on the list of datasets,
So that the list is more useful to me.

### Acceptance Criteria:

**On the list of datasets, the "Last Modified" value shown for each dataset follows these rules:**

For streaming datasets, use the "Data Last Ingested" value
- [ ] Display as "_DATE TIME_ (Last ingested)"
- Example: May Mobility Connected Electric Autonomous Vehicle Locations

For batch datasets, if the provider has provided a "Last Updated" value
- [ ] Display this value as "_DATE_ (Last updated by provider)"
- Example: COTA Trips

For batch datasets, if the provider did not provide a "Last Updated" value
- [ ] Display as "Last Updated date not provided"
- Example: COTA Real Time Bus Locations

For remote datasets, 
- [ ] Display "Updates to remote datasets are not tracked" 
- Example: OGRIP 100 Year Flood Plain -- CSV

**When the user requests to sort by last modified, sort in this order:**
- [ ] First, display datasets where a time is known, most recent first
- [ ] Treat batch datasets (which have a date but no time) as happening at 00:00 on the date given
- [ ] Second, list batch datasets with no date given
- [ ] Third, list remote datasets

### Tech Notes:

- Some datasets currently show "Update Pending".  This is not a valid and should not be displayed.  Example: COTA Real Time Bus Locations
- No changes are needed in the Dataset Details page. We're only changing the results page and the api

**Comment by rob-h-m** [comment]
Reviewed by Ram, he agrees with this approach

**Comment by ManApart** [comment]
This card has spawned issues in [Andi](https://github.com/smartcitiesdata/andi/issues/58) and [migration](https://github.com/SmartColumbusOS/migration/issues/214)
