### ISSUE TITLE
Save Info from Auth0

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/discovery_ui#203]
#### User Story:
As Connor
I would like to be able to have a personalized experience in the discovery apps
So that I can favorite datasets, create charts, and return to them in the future

#### Acceptance Criteria:
- [ ] Determine where to store the information - kicked this to discovery_api #247
- [ ] Store subscriber ID & email
- [ ] Don't store anything else

#### Technical Notes:
1.) ~~Something like Dynamo DB was discussed for the sake of estimating~~

#### Business Value:
1.) Lays the foundation for improved user experience in the OS through personalization
2.) Continued separation between public and restricted datasets
3.) Risk reduction by implementing through external account management services such as Google

#### Amigos:
@carriebrinkley , @JarredOlson

**Comment by abrock-accenture** [comment]
front-end:
- add API to our tenant
- start sending auth0 token as bearer token in our discovery api requests

back-end:
- validate token
- decode token, extracting user ID (and email?)
- do we need a new API to store/update user details
- decide where to store user details
