### ISSUE TITLE
Notify users that the login workflow has changed

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#208]
#### User Story:

As Connor 
I want to know that my workflow has changed for creating a login
So that there are no surprises and I maintain a positive user experience

#### Business Value: 

It is important to keep our users front-of-mind when building new features to help drive adoption.  Informing them that a workflow has changed should be a succinct communication that does not leave them in any dead ends. 

#### Acceptance Criteria: 

- [ ] Information is clearly displayed to users notifying them to the new login process 
- [ ] This will come in the form of a blurb about how to use auth0 on the hosted log in page - probably will look something like [this](https://auth0.auth0.com/login)
- [ ] Messaging contains a brief explanation behind "why" the process has changed 
- [ ] Messaging provides a link to the [existing reset password page](https://www.smartcolumbusos.com/reset-password) in the event the user is having trouble logging in.
- [ ] ... and how to revoke access from OAUTH providers

#### Technical Notes: 

- @jakeclark will provide UX direction and visual aids

#### Amigos: 

@carriebrinkley , @jakeclark, @JarredOlson

**Comment by abrock-accenture** [comment]
@carriebrinkley @rob-h-m Wasn't this card replaced by #217?

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #18](https://github.com/SmartColumbusOS/discovery/issues/18) via [**ZenHub**](https://www.zenhub.com/)
