### ISSUE TITLE
Connect auth0 to OAUTH provider: Google

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/discovery_ui#210]
#### User Story:

As Connor 
I would like to be able to have a personalized experience in the discovery apps
So that I can favorite datasets, create charts, and return to them in the future

#### Acceptance Criteria:

- [ ] Set up Google as a provider used with Auth0
- [ ] Users can log in to the OS using their Google accounts

#### Business Value: 

1.) Lays the foundation for improved user experience in the OS through personalization 
2.) Continued separation between public and restricted datasets 
3.) Risk reduction by implementing through Google

#### Amigos: 

@JarredOlson  , @carriebrinkley , @jakeclark

**Comment by rob-h-m** [comment]
9/11/19 - Started to refine, suspect we will get this "for free" as part of the auth0 implementation card.  Holding off until that card is played.

**Comment by carriebrinkley** [comment]
This card has been resolved "for free" with implementing Auth0.
