### ISSUE TITLE
Modify Auth0 login page to meet Smart Columbus branding standards

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#217]
As a part of implementing Auth0 in the OS, a login page was created.  One of the requirements for Auth0 to make it through IRB is that there is a user consent statement displayed informing the user what is happening and how their information will be used by the OS. 

Additionally, we would like to update the look of the Auth0 login page so that it appears more in line with Smart Columbus branding.

#### Acceptance Criteria: 

- [ ] The following language is displayed to the user on the Auth0 login page: This site use Auth0 as a third party authentication method, using accounts from known providers such as Google, instead of user IDs or passwords. Before proceeding, please ensure you have an account with one of these providers or use the sign-up process to create an account with Auth0.
- [ ] Pair with Jake Clark to update the look and feel of the login page to better match the rest of the site.  AKA, make it look less stale and sterile.  This work should be time boxed to 2 days.

#### Implementation Details: 

1. There is some flexibility as to how this login page can be customized.  Work with Jake Clark to determine how to make this language look appropriate on the screen.

#### Amigos: 

@jakeclark, @abrock-accenture

**Comment by ManApart** [comment]
Notes:
Quick test in API management sandbox.
HTTP PATCH this to https://auth0.com/docs/api/management/v2#!/Branding/patch_branding
```json
{
"logo_url": "https://discovery.smartcolumbusos.com/224f401510bbcb96eb733fcad6b6d593.png",
"favicon_url": "https://discovery.smartcolumbusos.com/224f401510bbcb96eb733fcad6b6d593.png",
"colors": {
"primary": "#00aeef",
"page_background": "#f7f7f7"
}
}
```
