### ISSUE TITLE
Create Separate Auth0 Tenants for Each Environment

### ISSUE THREAD

**Issue by abrock-accenture** [smartcitiesdata/discovery_ui#220]
As Andi,
I want to segregate accounts for different environment
So I can better control who has access

ACs:
- Set up auth0 tenants for local, dev, staging, and prod environments
- Update deploy configuration to use the correct Auth0 domain and client ID values for each environment
- use `smartcolumbusos-demo` tenant as an example.  Note the allowed origin and callback URLs that are currently configured for the only (default) app, as well as the JWT signature algorithm which is set to RS256 (under Advanced Settings -> OAuth)
- Creation of each environment should be easily repeatable to help minimize user error

Tech notes:
- Ideally, we should use Auth0's management APIs to script the creation of an environment (tenant, application, users?) so we can easily stand these up in a repeatable way
- Use *-smartos URLs

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #19](https://github.com/SmartColumbusOS/discovery/issues/19) via [**ZenHub**](https://www.zenhub.com/)
