### ISSUE TITLE
Redirect After Authentication Returns to Same URL

### ISSUE THREAD

**Issue by abrock-accenture** [smartcitiesdata/discovery_ui#221]
As a user of the Discovery UI,
I want to return to the same place after logging in
So my workflow is not interrupted

ACs:
- Upon returning to the Discovery UI OAuth URL, the user should be redirected back to the page they were on when they left (i.e. https://discovery.staging-smartos.com/?facets%5Borganization%5D%5B%5D=Central%20Ohio%20Transit%20Authority&apiAccessible=true)
- This should work for any page where the user can login

Tech Notes:
- See here for the Auth0 recommendation on how to do this, storing the path/query string as part of the state variable in session storage: https://community.auth0.com/t/allowed-callback-urls-ending-with-a-wildcard/7626

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #20](https://github.com/SmartColumbusOS/discovery/issues/20) via [**ZenHub**](https://www.zenhub.com/)
