### ISSUE TITLE
Plotly Styling in IE

### ISSUE THREAD

**Issue by abrock-accenture** [smartcitiesdata/discovery_ui#227]
![plotly-chart-editor-ie11.png](https://images.zenhubusercontent.com/5d406655ca7b4e0001322b7b/ba7bc7a0-b9a0-4bda-9a6c-ce626341ee5a)
![visualize-button-ie11.png](https://images.zenhubusercontent.com/5d406655ca7b4e0001322b7b/cb38370e-b947-4ee0-a7cb-a0614109ede1)
![visualize-button-edge.png](https://images.zenhubusercontent.com/5d406655ca7b4e0001322b7b/86772e62-5647-4ebe-8873-e24550f85ce3)

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #22](https://github.com/SmartColumbusOS/discovery/issues/22) via [**ZenHub**](https://www.zenhub.com/)
