### ISSUE TITLE
Search is not executed when a user inputs from home page.

### ISSUE THREAD

**Issue by cameronmarsh** [smartcitiesdata/discovery_ui#238]
Current behavior: When a user enters a search from the smartcolumbusos.com home page, the text is copied to the search box on the discovery-ui but the search is not executed.

Expected behavior: Same as above but the search results are returned.

Reason: It causes confusion as the use thinks they are viewing results from their search parameter.

**Comment by cameronmarsh** [comment]
This should get cleared up with removal of the iframe.

**Comment by ManApart** [comment]
On further inspection we realized that this will **not** get cleaned up with iframe removal. If you copy a link with a search query param and then paste it into a window, it does **not** execute the query on first load.
