### ISSUE TITLE
Store information_schema.columns table

### ISSUE THREAD

**Issue by cameronmarsh** [smartcitiesdata/discovery_ui#239]
Value Statement: Improves performance of the "Data to join with..." functionality

AC:
- Store the information_schema (table_name, type, and column_name fields) in redis on dataset ingest.
- Discovery API pulls the "Data to join with..." from redis.

**Comment by cameronmarsh** [comment]
blocked on #241

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #25](https://github.com/SmartColumbusOS/discovery/issues/25) via [**ZenHub**](https://www.zenhub.com/)
