### ISSUE TITLE
Display datasets with column names that appear in my current dataset

### ISSUE THREAD

**Issue by cameronmarsh** [smartcitiesdata/discovery_ui#242]
As a data consumer, I would like to see which datasets can be joined with my current query so that I can easily add data to a plot.ly visualization

#### Acceptance Criteria

- [ ] List of datasets returned from the API card (#241 )
- [ ] Add example of how to a join query

#### Stretch goals

- [ ] Display column names of datasets 

#### Notes
- This is a thin slice of making the list of datasets links that can automatically join to the current query
- Depends on API endpoint described in discovery_ui#241
- Talk to @jakeclark for details

#### Amigos

@cameronmarsh , @jakeclark, @carriebrinkley

**Comment by ManApart** [comment]
How do we know programmatically which datasets can be joined? Or is this just a manually curated list?

**Comment by rob-h-m** [comment]
Issue moved to [SmartColumbusOS/discovery #23](https://github.com/SmartColumbusOS/discovery/issues/23) via [**ZenHub**](https://www.zenhub.com/)
