### ISSUE TITLE
Create a dataset breadcrumb on the visualization page

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#244]
As an SCOS user
When I navigate to create a visualization of a dataset, I want to be able to know which dataset I am working off of 
So that I don't lose context about the visualization I am trying to build

#### Business Value

Currently, when a user navigates to the visualization page within a dataset, they are given the option to navigate back to the dataset if they need to.  The problem that is being experienced is that users have a tendency to forget exactly what dataset they're working off of, and when they navigate back to the dataset, the context is lost on the visualization.  

#### Acceptance Criteria

- [ ] When I am on the visualization page of a dataset, a breadcrumb exists to make me aware of the dataset I am working on 
- [ ] If multiple datasets are joined in the SQL query, multiple breadcrumbs exist
- [ ] @jakeclark will consult on the UX throughout 

#### Amigos

@jakeclark , @carriebrinkley

**Comment by jakeclark** [comment]
One example: Utilizing the existing "back to dataset" link to include the dataset name, giving context to what the user is looking at.  <img width="1299" alt="breadcrumb1" src="https://user-images.githubusercontent.com/430082/65615825-faa1d680-df87-11e9-84f3-d75318ede47f.png">

**Comment by jakeclark** [comment]
Another option, the traditional breadcrumb approach: 
<img width="1297" alt="breadcrumb2" src="https://user-images.githubusercontent.com/430082/65616236-b95df680-df88-11e9-96db-6fb562b21e99.png">

**Comment by rob-h-m** [comment]
Closing - not needed if we do #193
