### ISSUE TITLE
Create new filter(s) for visualization datasets

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#245]
We have received feedback that it is challenging to locate datasets in the OS that are good candidates for creating visualizations.  In an attempt to improve this user experience, Ram has worked to curate a list of datasets that visualize well, and we would like to make these datasets easy to identify/access.

#### Acceptance Criteria

- [ ] The datasets on @ramboyapati 's list have all been tagged with "visualization"
- [ ] The left-hand navigation has been updated to allow the user to check a box and be taken to all datasets identified by Ram
- [ ] The search bar allows users to navigate to the curated list of "visualization" datasets
- [ ] @jakeclark will consult along the way for UX

**Comment by rob-h-m** [comment]
Doing this in different way - closing
