### ISSUE TITLE
OWASP ZAP scan is producing a new error

### ISSUE THREAD

**Issue by ManApart** [smartcitiesdata/discovery_ui#247]
The [latest scan](https://jenkins.alm.internal.smartcolumbusos.com/job/Joomla%20Prod%20OWASP/job/owasp/6/console) produced a new error/warn: `WARN-NEW: Format String Error [30002] x 28 `.

AC:
- This warn should be fixed and new scans no longer report it.

**Comment by rob-h-m** [comment]
Play after joomla_deploy 5

**Comment by rob-h-m** [comment]
Closing - combined into joomla_deploy 5
