### ISSUE TITLE
Fix button styling in IE and Firefox

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/discovery_ui#256]
When a user accesses a dataset in IE or Firefox, the "visualize" button becomes extremely large.  

Acceptance Criteria: 

- [ ] The styling of buttons is the same regardless of the browser the user is working in
- [ ] All other buttons have been checked (Visualize is the first one that was noticed)

**Comment by rob-h-m** [comment]
Already fixed by another change
