### ISSUE TITLE
Discovery UI/API - multiple formats of dataset available for download

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/discovery_ui#87]
"As a data consumer, 
I want a better data discovery experience,
So that I can find data in the platform more easily.

Acceptance criteria:

TBD (see Big Jake's mockup)

Technical notes:

TBD

06-24-19: Migrated from SMRT-1404"

**Comment by rob-h-m** [comment]
rejected 08/14/19 by Carrie and Johnson
