### ISSUE TITLE
Restricted datasets - Ingest large Inrix dataset

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/discovery_ui#88]
"As a data consumer I would like to have the existing CKAN data available in the new discovery ui so that I can access the datasets I already know and love.

AC: 
 * 239bf65d-5bc7-4a49-ae00-070de3c8a369 ingested

Tech notes:
 * Reaper is currently timing out on download (10min)
 * Reaper is being updated and might be able to handle it with new process
 * 4.3GB

 

06-24-19: Migrated from SMRT-1265"

**Comment by rob-h-m** [comment]
Duplicate of scosopedia #13
